name: pipeline

on:
  push:

  
jobs:
  build:
    runs-on: ubuntu-latest

        
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - run: mvn test  
    
    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2.0.1
    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"    
    
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/

  code-analisys:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
        
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=joseribas89_Devops-Fiap-ON

  publish:
    runs-on: ubuntu-latest
    needs: code-analisys   
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          package: '*.jar'
      - name: Publish package
        run: mvn -Dmaven.resolver.transport=wagon -B package --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
          
  deploy-STG:
    runs-on: ubuntu-latest
    environment:
      name: stg
    needs: publish
    
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy 
        shell: bash
        run: |
          echo "Deploy STG"
          
    
  deploy-Pre:
    runs-on: ubuntu-latest
    env: 
      NEEDCUSTOM : publish

    if: github.ref == 'refs/heads/release'
    environment:
      name: pre
    needs: publish
    steps:
      - name: Deploy 
        shell: bash
        run: |
          echo "Deploy PRE"
          
          
  security-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git init
      - name: Check for passwords/secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          # Exclude some file patterns from the scan
          exclude: '*.md,*.txt'
          # Set up the rules to search for passwords/secrets
          # You can customize these rules based on your requirements
          flags: --pretty --redact --repo-config=gitleaks.toml
        env:
          # Pass the GitHub token to the action
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



